# Generated by Django 4.1.5 on 2023-03-12 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappstaff', '0002_alter_add_durable_image_alter_add_durable_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_CategoryStatus', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='add_durable',
            name='status',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='status_durable', to='myappstaff.categorystatus'),
        ),
        migrations.AlterField(
            model_name='add_parcel',
            name='status',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='status_parcel', to='myappstaff.categorystatus'),
        ),
    ]
